### ISSUE TITLE
Web map is broken when using advanced configuration. Help needed.

### ISSUE THREAD

**Issue by nate2014jatc** [webbukkit/DynmapCore#102]
I have two MC Servers, $Vanilla and $Modded.
$Vanilla and $Modded talk to $DatabaseServer for tile storage. 
This part seems to be working correctly.
I'm hosting the `web/` files from each server in different subfolders on my domain ($Domain.info/Modded and $Domain.info/Vanilla.
The $DatabaseServer is also the web server.

From the Server side, everything appears to be working fine, however the tiles/markers/players don't update.

I'll attach my configs below.
[Modded_configuration.txt](https://github.com/webbukkit/DynmapCore/files/2544979/Modded_configuration.txt)
[Vanilla_configuration.txt](https://github.com/webbukkit/DynmapCore/files/2544980/Vanilla_configuration.txt)

**Comment by jwshields** [comment]
Does the user that Minecraft/Bukkit/Dynmap/etc is running as, have permission to write to `/var/www/html/Maps/`?
That is more than likely the issue here.
For my config, I didn't want to muck about with awkward permissions, so I symlinked my www/maps directory to where Dynmap was writing the web files and my web server would traverse the symlink to serve the files

**Comment by nate2014jatc** [comment]
Dynmap doesn't seem to write anything to `/var/www/html/Maps` because all the storage appears to be forwarded to the MySQL server

**Comment by jwshields** [comment]
So, your `webpath` config option, that points to the `/var/www/html/Maps` directory
Dynmap needs to be able to write to it in order to send the JSON updates, so that clients know which map files to request (and your http/php daemon to know what files to get from mysql)

**Comment by nate2014jatc** [comment]
How would you recommend getting those files from $Vanilla to $WebServer?

**Comment by jwshields** [comment]
Either symlink the directory to a place that minecraft can write to, or change the webpath to be the proper path & give the user permissions to write to that directory

**Comment by nate2014jatc** [comment]
I think there may have been a miscommunication. $Vanilla and $WebServer are separate physical machines. Would you recommend that I set up something to move items between the servers?

**Comment by nate2014jatc** [comment]
I (somewhat) solved this issue by mounting the $Vanilla `/var/www/html/Maps/Vanilla` directory to the $WebServer `/var/www/html/Maps/Vanilla` directory with a SSHFS rule in my FSTab, using key-based authentication to automate the process and make it as seamless as possible.
```
nate@192.168.1.127:/var/www/html/Maps/Vanilla /var/www/html/Maps/Vanilla fuse.sshfs port=22,default_permissions,_netdev,allow_other,norelatime,umask=000 0 0
```
