### ISSUE TITLE
Possible bug in BukkitVersionHelperGeneric?

### ISSUE THREAD

**Issue by Scopelabz** [webbukkit/DynmapCore#61]
Hey there!

I was trying to get Dynmap to render a biome overview and noticed some of the new (mutated) ones were just being grey as if they weren't properly recognized. I've traced the possible error back to BukkitVersionHelperGeneric - biomebasearray does not seem to have been initialized at all - which prevented getPrivateField(...) from accessing the "biome" property of CraftChunkSnapshot.

I was able to fix this by going to line 111

``` java
/* CraftChunkSnapshot */
craftchunksnapshot = getOBCClass("org.bukkit.craftbukkit.CraftChunkSnapshot");
ccss_biome = getPrivateField(craftchunksnapshot, new String[] { "biome" }, biomebasearray);
```

and adding a few lines of code as follows

``` java
/* CraftChunkSnapshot */
craftchunksnapshot = getOBCClass("org.bukkit.craftbukkit.CraftChunkSnapshot");

Class<?> bbaseClass = getNMSClass("net.minecraft.server.BiomeBase");
biomebasearray = (java.lang.reflect.Array.newInstance(bbaseClass, 1)).getClass();

ccss_biome = getPrivateFieldNoFail(craftchunksnapshot, new String[] { "biome" }, biomebasearray);
```

Dunno, maybe you can use this information somehow which is why I thought I'd open a ticket here. (:

Regards,
Matthias

**Comment by Developaws** [comment]
This issue was fixed here;

https://github.com/webbukkit/dynmap/commit/27dc1d4a0b2a3e0d1048af208f4716a431795c5b#diff-5dd7c8fbc414280997a95fa16a456bcd
