### ISSUE TITLE
[Vulnerability] Accessible the /standalone/MySQL_config.php file

### ISSUE THREAD

**Issue by ken-kentan** [webbukkit/DynmapCore#72]
This MySQL_config.php file include the MySQL host, port, user id and password data.

All user can access this file, and read with plain text.

Original Japanese report:
https://blog.kentan.jp/2016/10/27/dynmap_security_hole/

**Comment by mikeprimm** [comment]
THe file is only used if an external web server is configured, in which case it is executed and does not return the plain text.  If it isn't being used, it will not contain credentials.
