### ISSUE TITLE
MySQL V5.5.45&up + Dynmap 2.5 = SSL Errors

### ISSUE THREAD

**Issue by jwshields** [webbukkit/DynmapCore#90]
Hello!

I recently upgraded my Debian machine from MySQL 5.5 to 5.7.19;

Since that update my console log in Spigot/Bukkit has been slowly flowing with MySQL connection errors.

```
[06:39:44] [Dynmap Render Thread/WARN]: Thu Sep 07 06:39:44 PDT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
```

I do not wish to use SSL for the connection to my DB, but nonetheless, as stated in the error, after MySQL version 5.5.45, if the ssl argument is not explicitly called, the connection throws warnings.
I was looking over the code and it seems something on one of these lines...
https://github.com/webbukkit/DynmapCore/blob/master/src/main/java/org/dynmap/storage/mysql/MySQLMapStorage.java#L289
https://github.com/webbukkit/DynmapCore/blob/master/src/main/java/org/dynmap/storage/mysql/MySQLMapStorage.java#L516

To make a suggestion, would it be possible to add a parameter to the configuration.txt file ( https://github.com/webbukkit/dynmap/blob/master/src/main/resources/configuration.txt )
Such as a boolean "sslenabled" true/false under storage for mysql? (Optionally verify cert if sslenabled=true?)

and for the jdbc uri in the MySQLMapStorage.java file, an option appended to the connection string such as verifyServerCertificate=false or useSSL=[false|true]
to account for self signed or even whether or not to use ssl.

**Comment by rouing** [comment]
I would switch to MairaDB over MySQL as there is major improvements and it is a drop in replacement. I will work on a pull request to add this option as I would like to see the option of having SSL on the connection anyways.

**Comment by nate2014jatc** [comment]
bumping this. The hardcoded option "?allowReconnect=true" causes the previous fix to cause more severe errors.

(previous fix being that you add "?useSSL=false" to your database name.)

**Comment by rouing** [comment]
@nate2014jatc Ayeyeye. 

This needs to be ported to a config based option.

**Comment by aharabedian** [comment]
Is there any update on this issue? I am having the same issue with the hardcoded "?allowReconnect=true" flag.

**Comment by jwshields** [comment]
Add the `?useSSL=false` after the `?allowReconnect=true`

**Comment by aharabedian** [comment]
the `?allowReconnect=true` flag is hard coded into DynMap, there is not a config option to add another flag. If you add the `?useSSL=false` to the end of the database name, it causes an issue with the hard-coded flag and DynMap fails to connect to the database.

**Comment by nate2014jatc** [comment]
I can confirm. I'm still getting griped at to enable SSL and provide a truststore or globally disable SSL (not happening).

**Comment by aharabedian** [comment]
I created a fix and submitted a pull request. I have been using my build of v3.0 for the past day on my spigot server and it has been working fine, no SSL errors. If you build from my repo it will add a configuration option for flags. Hopefully it gets added as a feature.

**Comment by rouing** [comment]
I am the one who hardcoded the allow reconnect true and had the PR. This was to fix a DIFFERENT issue with latest versions of MYSQL/MARIADB dropping connections and not being allowed to connect.  At this point, I am going to redo this to have a config to allow the use of a URI instead of user/pass/host/port by itself.
